#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : require

#include "double_double.glsl"

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer InputSpectrum {
  DoubleDoubleComplex values[];
} input_spectrum;

layout(std430, binding = 1) buffer AccumulatedSpectrum {
  DoubleDoubleComplex values[];
} accumulated_spectrum;

layout(push_constant) uniform Parameters {
  uint spectrum_bins;
} parameters;

void main()
{
  const uint index = gl_GlobalInvocationID.x;

  if (index < parameters.spectrum_bins) {
    const DoubleDoubleComplex first =
        accumulated_spectrum.values[index];
    const DoubleDoubleComplex second = input_spectrum.values[index];
    DoubleDoubleComplex result;

    result = multiply_complex_dd(first, second);
    accumulated_spectrum.values[index] = result;
  }
}
