/* SoX configuration header - generated by CMake */

#ifndef SOXCONFIG_H
#define SOXCONFIG_H

#define PACKAGE "sox"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"

/* External library usage */
#cmakedefine EXTERNAL_GSM             1
#cmakedefine EXTERNAL_LPC10           1

/* Audio device drivers */
#cmakedefine HAVE_ALSA                1
#cmakedefine HAVE_AO                  1
#cmakedefine HAVE_COREAUDIO           1
#cmakedefine HAVE_OSS                 1
#cmakedefine HAVE_PULSEAUDIO          1
#cmakedefine HAVE_SNDIO               1
#cmakedefine HAVE_SUN_AUDIO           1
#cmakedefine HAVE_WAVEAUDIO           1

/* Audio formats */
#cmakedefine HAVE_AMRNB               1
#cmakedefine HAVE_AMRWB               1
#cmakedefine HAVE_OPENCORE_AMRNB_INTERF_DEC_H 1
#cmakedefine HAVE_OPENCORE_AMRWB_DEC_IF_H 1
#cmakedefine HAVE_FLAC                1
#cmakedefine HAVE_GSM                 1
#cmakedefine HAVE_ID3TAG              1
#cmakedefine HAVE_LPC10               1
#cmakedefine HAVE_MAD_H               1
#cmakedefine HAVE_LAME_LAME_H         1
#cmakedefine HAVE_LAME                1
#cmakedefine HAVE_TWOLAME             1
#cmakedefine HAVE_TWOLAME_H           1
#cmakedefine HAVE_MP3                 1
#cmakedefine HAVE_OGG_VORBIS          1
#cmakedefine HAVE_OPUS                1
#cmakedefine HAVE_SNDFILE             1
#cmakedefine HAVE_WAVPACK             1

/* Other features */
#cmakedefine HAVE_LADSPA_H            1
#cmakedefine HAVE_LIBLTDL             1
#cmakedefine HAVE_MAGIC               1
#cmakedefine HAVE_PNG                 1
#cmakedefine HAVE_OPENMP              1

/* Standard headers */
#cmakedefine HAVE_BYTESWAP_H          1
#cmakedefine HAVE_FCNTL_H             1
#cmakedefine HAVE_FENV_H              1
#cmakedefine HAVE_GLOB_H              1
#cmakedefine HAVE_INTTYPES_H          1
#cmakedefine HAVE_IO_H                1
#cmakedefine HAVE_STDINT_H            1
#cmakedefine HAVE_STRING_H            1
#cmakedefine HAVE_STRINGS_H           1
#cmakedefine HAVE_SYS_AUDIOIO_H       1
#cmakedefine HAVE_SUN_AUDIOIO_H       1
#cmakedefine HAVE_SYS_SOUNDCARD_H     1
#cmakedefine HAVE_MACHINE_SOUNDCARD_H 1
#cmakedefine HAVE_SYS_STAT_H          1
#cmakedefine HAVE_SYS_TIMEB_H         1
#cmakedefine HAVE_SYS_TIME_H          1
#cmakedefine HAVE_SYS_TYPES_H         1
#cmakedefine HAVE_SYS_UTSNAME_H       1
#cmakedefine HAVE_TERMIOS_H           1
#cmakedefine HAVE_UNISTD_H            1
#cmakedefine HAVE_SYS_IOCTL_H         1

/* Functions */
#cmakedefine HAVE_FMEMOPEN            1
#cmakedefine HAVE_FSEEKO              1
#cmakedefine HAVE_GETTIMEOFDAY        1
#cmakedefine HAVE_LRINT               1
#cmakedefine HAVE_MKSTEMP             1
#cmakedefine HAVE_POPEN               1
#cmakedefine HAVE_STRCASECMP          1
#cmakedefine HAVE_STRDUP              1
#cmakedefine HAVE_VSNPRINTF           1

/* System properties */
#cmakedefine WORDS_BIGENDIAN          1

/* Windows-specific */
#cmakedefine HAVE_WIN32_GLOB_H        1
#cmakedefine HAVE_WIN32_LTDL_H        1

/* LADSPA path */
#cmakedefine LADSPA_PATH "@LADSPA_PATH@"

/* Plugin library directory */
#ifndef PKGLIBDIR
#define PKGLIBDIR "."
#endif

#endif /* SOXCONFIG_H */
